name: Deploy APIs

on:
  workflow_dispatch:

jobs:
  deploy:
    env:
      dashboard_url: https://universal-guitarist-adm.aws-use1.cloud-ara.tyk.io/
      dash_key: ${{ secrets.DASHBOARD_SECRET }}
    runs-on: ubuntu-latest
    name: Deploy Tyk APIs
    steps:
     - run: echo "starting sync"
     - run: echo "${{ runner.os }} operating system"
     - run: echo "$dashboard_url"
     - name: Check Out
       uses: actions/checkout@v4
     - run: |
         curl -s https://packagecloud.io/install/repositories/tyk/tyk-sync/script.deb.sh | sudo bash
     - run: |
         sudo apt-get install tyk-sync=1.5.0
     - run: |
         /opt/tyk-sync/tyk-sync sync -d="$dashboard" -s="$dash_key" -p="."
