name: Deploy APIs

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'api-*.json'
      - 'oas-*.json'
      - 'policy-*.json'
      - '.tyk.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Tyk APIs
    
    env:
      DASHBOARD_URL: ${{ secrets.DASHBOARD_URL }}
      DASH_KEY: ${{ secrets.DASH_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tyk Sync
        run: |
          curl -s https://packagecloud.io/install/repositories/tyk/tyk-sync/script.deb.sh | sudo bash
          sudo apt-get install tyk-sync=2.0.0
        
      - name: Sync APIs
        run: |
          if ! /opt/tyk-sync/tyk-sync sync -d="${DASHBOARD_URL}" -s="${DASH_KEY}" -p="."; then
            echo "Failed to sync APIs"
            exit 1
          fi
